/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;



/**
 *
 * @author estudiante
 */
public class FormDepartamento extends javax.swing.JFrame {

    private FormPrincipal myPrin;

    /**
     * Creates new form FormDepartamento
     */
    public FormDepartamento(FormPrincipal p) {
        this.myPrin = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cmbRegistrar = new javax.swing.JButton();
        txtNomDepar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbDepartamentos = new javax.swing.JComboBox();
        cmdCargarDepartamnetos = new javax.swing.JButton();
        lblCargarDepartamentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cmdReporte = new javax.swing.JButton();
        cmbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEPARTAMENTO");

        cmbRegistrar.setText("Registrar");
        cmbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRegistrarActionPerformed(evt);
            }
        });

        txtNomDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomDeparActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Departamento:");

        cmbDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentosActionPerformed(evt);
            }
        });

        cmdCargarDepartamnetos.setText("Cargar");
        cmdCargarDepartamnetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarDepartamnetosActionPerformed(evt);
            }
        });

        lblCargarDepartamentos.setText("Cargar Departamentos:");

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblCargarDepartamentos))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomDepar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(cmbDepartamentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdCargarDepartamnetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(92, 92, 92))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRegistrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCargarDepartamnetos)
                    .addComponent(lblCargarDepartamentos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultar", jPanel3);

        cmdReporte.setText("REPORTE");
        cmdReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReporteActionPerformed(evt);
            }
        });

        cmbSalir.setText("SALIR");
        cmbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(cmdReporte)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdReporte)
                    .addComponent(cmbSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmbSalirActionPerformed

    private void cmdReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReporteActionPerformed
        // TODO add your handling code here:
        FormReportes r = new FormReportes(this, null);
        r.setVisible(true);
    }//GEN-LAST:event_cmdReporteActionPerformed

    private void cmbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRegistrarActionPerformed
        // TODO add your handling code here:
        String nomD = this.txtNomDepar.getText();

        if (nomD.isEmpty()) {
            Ventana.imp("INGRESE DEPARTAMENTO", "SISTEMA");
            return;
        }
        String cad = this.myPrin.getMyCenso().registrarDepartamento(nomD);
        Ventana.imp(cad, "SISTEMA");


        this.txtNomDepar.setText("");
    }//GEN-LAST:event_cmbRegistrarActionPerformed

    private void cmdCargarDepartamnetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarDepartamnetosActionPerformed
        // TODO add your handling code here:
        
        this.cmbDepartamentos.removeAllItems();
     
        String nomDep = this.myPrin.getMyCenso().cargarDepartamentos();
        
        if (nomDep.isEmpty()){
            Ventana.imp("REGISTRE AL MENOS UN DEPARTAMENTO", "SISTEMA");
            return;
        }
        
        this.cmbDepartamentos.addItem("No Seleccion");
          
        String []aux=nomDep.split("/");
        for (String x:aux){
            this.cmbDepartamentos.addItem(x);
        } 
        
    }//GEN-LAST:event_cmdCargarDepartamnetosActionPerformed

    private void cmbDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentosActionPerformed
        // TODO add your handling code here:
        if (this.cmbDepartamentos.getItemCount() > 0){
        String cad = this.cmbDepartamentos.getSelectedItem().toString();
         
        if (!cad.equals("No Seleccion")){
            String c= this.myPrin.getMyCenso().consultarDepartamento(cad);
            this.txtMostrar.setText(c);
        }
         }
        
    }//GEN-LAST:event_cmbDepartamentosActionPerformed

    private void txtNomDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomDeparActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNomDeparActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDepartamentos;
    private javax.swing.JButton cmbRegistrar;
    private javax.swing.JButton cmbSalir;
    private javax.swing.JButton cmdCargarDepartamnetos;
    private javax.swing.JButton cmdReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCargarDepartamentos;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtNomDepar;
    // End of variables declaration//GEN-END:variables
}
