/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;

/**
 *
 * @author Estudiante
 */
public class FormMunicipio extends javax.swing.JFrame {

    private FormPrincipal myPrin;

    /**
     * Creates new form FormCenso
     */
    public FormMunicipio(FormPrincipal p) {
        this.myPrin = p;
        initComponents();
        this.deshabilitarBotones();

    }

    public FormPrincipal getMyPrin() {
        return myPrin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalMujeres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdadPromedio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIngresoPromedio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTemperaturaMedia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmdRegistrar = new javax.swing.JButton();
        cmdVerificarMun = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtCedulaAlcalde = new javax.swing.JTextField();
        cmdReporte = new javax.swing.JButton();
        cmbSalir = new javax.swing.JButton();
        cmdCargarDepartamento = new javax.swing.JButton();
        cmbDepartamentoR = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmdVeificarAlcalde = new javax.swing.JButton();
        cmdRequerientoQuiez = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtCantidadIngresProm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMostrarConsolidado = new javax.swing.JTextArea();
        cmdConsolidado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmbDepartamentoR1 = new javax.swing.JComboBox();
        cmdCargarDepartamento1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbMunicipioAlcalde = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMostrarMuni = new javax.swing.JTextArea();
        cmdEliminarAlcaldeM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MUNICIPIO");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("AGREGAR MUNICIPIO");

        jLabel3.setText("Nombre de Municipio");

        jLabel4.setText("Total Mujeres");

        jLabel5.setText("Total Hombres");

        jLabel6.setText("Edad Promedio");

        jLabel7.setText("Ingreso Promedio");

        jLabel8.setText("Temperatura Media");

        jLabel10.setText("Categoria <1..5>: ");

        cmdRegistrar.setText("REGISTRAR");
        cmdRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarActionPerformed(evt);
            }
        });

        cmdVerificarMun.setText("VERIFICAR");
        cmdVerificarMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerificarMunActionPerformed(evt);
            }
        });

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel9.setText("Cedula del Alcalde:");

        cmdReporte.setText("REPORTE");
        cmdReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReporteActionPerformed(evt);
            }
        });

        cmbSalir.setText("SALIR");
        cmbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalirActionPerformed(evt);
            }
        });

        cmdCargarDepartamento.setText("CARGAR");
        cmdCargarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarDepartamentoActionPerformed(evt);
            }
        });

        cmbDepartamentoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoRActionPerformed(evt);
            }
        });

        jLabel2.setText("Departamentos");

        cmdVeificarAlcalde.setText("VERIFICAR");
        cmdVeificarAlcalde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVeificarAlcaldeActionPerformed(evt);
            }
        });

        cmdRequerientoQuiez.setText("requerimiento quiez");
        cmdRequerientoQuiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRequerientoQuiezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 130, Short.MAX_VALUE)
                        .addComponent(cmdRequerientoQuiez)
                        .addGap(18, 18, 18)
                        .addComponent(cmdReporte)
                        .addGap(31, 31, 31)
                        .addComponent(cmdRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2))
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cmbDepartamentoR, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtNombreM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cmdVerificarMun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cmdCargarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtTotalMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTotalHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEdadPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIngresoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cmbCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTemperaturaMedia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtCedulaAlcalde, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cmdVeificarAlcalde)))))))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartamentoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCargarDepartamento)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdVerificarMun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalHombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEdadPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngresoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTemperaturaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCedulaAlcalde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdVeificarAlcalde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRegistrar)
                    .addComponent(cmdReporte)
                    .addComponent(cmbSalir)
                    .addComponent(cmdRequerientoQuiez))
                .addContainerGap())
        );

        jTabbedPane1.addTab("REGISTRAR MUNICIPIO", jPanel1);

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jLabel11.setText("VALOR INGRESO PROMEDIO :");

        jButton1.setText("CALCULAR INGRESO PROMEDIO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadIngresProm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCantidadIngresProm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTAR POR INGRESO PROM MAYOR", jPanel2);

        txtMostrarConsolidado.setColumns(20);
        txtMostrarConsolidado.setRows(5);
        jScrollPane2.setViewportView(txtMostrarConsolidado);

        cmdConsolidado.setText("CONSOLIDADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(cmdConsolidado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdConsolidado)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSOLIDADO", jPanel3);

        jLabel12.setText("Departamentos");

        cmbDepartamentoR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoR1ActionPerformed(evt);
            }
        });

        cmdCargarDepartamento1.setText("CARGAR");
        cmdCargarDepartamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarDepartamento1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Municipios con Alcalde: ");

        cmbMunicipioAlcalde.setEnabled(false);
        cmbMunicipioAlcalde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMunicipioAlcaldeActionPerformed(evt);
            }
        });

        txtMostrarMuni.setEditable(false);
        txtMostrarMuni.setColumns(20);
        txtMostrarMuni.setRows(5);
        jScrollPane3.setViewportView(txtMostrarMuni);

        cmdEliminarAlcaldeM.setText("QUITAR ALCALDE - MUNICIPIO");
        cmdEliminarAlcaldeM.setEnabled(false);
        cmdEliminarAlcaldeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarAlcaldeMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDepartamentoR1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMunicipioAlcalde, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(cmdCargarDepartamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(cmdEliminarAlcaldeM, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartamentoR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCargarDepartamento1)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbMunicipioAlcalde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdEliminarAlcaldeM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESASIGNAR ALCALDE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReporteActionPerformed
        // TODO add your handling code here:
        FormReportes r = new FormReportes(null, this);
        r.setVisible(true);
    }//GEN-LAST:event_cmdReporteActionPerformed

    private void cmbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmbSalirActionPerformed

    private void cmdCargarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarDepartamentoActionPerformed
        // TODO add your handling code here:

        this.cmbDepartamentoR.removeAllItems();
        String cad = this.myPrin.getMyCenso().cargarDepartamentos();

        if (!cad.isEmpty()) {
            this.cmbDepartamentoR.addItem("No Sleccion");
            String[] n = cad.split("/");

            for (String nomD : n) {
                this.cmbDepartamentoR.addItem(nomD);

            }
            this.cmdVerificarMun.setEnabled(true);
            this.txtNombreM.setEnabled(true);
        }

        this.limpiar();
    }//GEN-LAST:event_cmdCargarDepartamentoActionPerformed

    private void cmdVerificarMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerificarMunActionPerformed
        // TODO add your handling code here:

        String nomD = this.cmbDepartamentoR.getSelectedItem().toString();
        String nomM = this.txtNombreM.getText();
        if (nomD.equals("No Sleccion")) {
            Ventana.imp("escoja departamento", "Sistema");
            return;
        }
        if (nomM.isEmpty()) {
            Ventana.imp("Digite un Municipio", "Sistema");
            return;
        }
        
        if (this.myPrin.getMyCenso().validarExistMuni(nomD, nomM)) {
            Ventana.imp("Municipio Ya Exixte,Digite Otro", "Sistema");
            return;
        }
        this.habilitarBotones();
    }//GEN-LAST:event_cmdVerificarMunActionPerformed

    private void cmdRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarActionPerformed
        // TODO add your handling code here:
        String nomD = this.cmbDepartamentoR.getSelectedItem().toString();
        String nomM = this.txtNombreM.getText().toString();
        String totalMujere = this.txtTotalMujeres.getText().toString();
        String totalHombre = this.txtTotalHombre.getText().toString();
        String edadProm = this.txtEdadPromedio.getText().toString();
        String ingresosprom = this.txtIngresoPromedio.getText().toString();
        String tempMedia = this.txtTemperaturaMedia.getText().toString();
        String categoria = this.cmbCategoria.getSelectedItem().toString();
        String cedAlcade = this.txtCedulaAlcalde.getText().toString();

        if (nomM.isEmpty() || totalMujere.isEmpty() || totalHombre.isEmpty() || edadProm.isEmpty()
                || ingresosprom.isEmpty() || tempMedia.isEmpty()) {
            Ventana.imp("Se Necesitan Llenar Campos", "Sistema");
            return;
        } 
          String cad = this.myPrin.getMyCenso().agregarMunicipio(nomM, Integer.parseInt(totalMujere),
          Integer.parseInt(totalHombre), Integer.parseInt(edadProm), Integer.parseInt(ingresosprom),
          Integer.parseInt(tempMedia), Integer.parseInt(categoria), cedAlcade, nomD);
          Ventana.imp(cad, "Sistema");

       
        this.limpiar();
        this.deshabilitarBotones();
    }//GEN-LAST:event_cmdRegistrarActionPerformed

    private void cmdVeificarAlcaldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVeificarAlcaldeActionPerformed
        // TODO add your handling code here:

        String cedula = this.txtCedulaAlcalde.getText();
        if (cedula.isEmpty()) {
            Ventana.imp("Digite Cedula Alcalde", "Sistema");
            return;
        }
        if (!this.myPrin.getMyCenso().validarAlcalde(cedula)) {
               this.txtCedulaAlcalde.setEnabled(false);
                FormAlcalde a = new FormAlcalde(this, cedula);
                a.setVisible(true);
                this.cmdRegistrar.setEnabled(true);
        }   
        else {
           if (this.myPrin.getMyCenso().buscarEntreMunicipios(cedula)) {
                Ventana.imp("Digite Otra Cedula\nPorque El Alcalde Ya ESta Asignado", "Sistema");
                this.txtCedulaAlcalde.setText("");
                
            } else {
                Ventana.imp("Continue Con El Registro del Municipio", "Sistema");
                this.cmdRegistrar.setEnabled(true);
                
            }
        }
    }//GEN-LAST:event_cmdVeificarAlcaldeActionPerformed

    private void cmdRequerientoQuiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRequerientoQuiezActionPerformed
        // TODO add your handling code here:
        formFormularioQuiez p = new formFormularioQuiez(this);
        p.setVisible(true);
    }//GEN-LAST:event_cmdRequerientoQuiezActionPerformed

    private void cmdCargarDepartamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarDepartamento1ActionPerformed
        // TODO add your handling code here:
          this.cmbDepartamentoR1.removeAllItems();
         
        String c = this.myPrin.getMyCenso().cargarDepartamentos();
        if (c.isEmpty()){
           Ventana.imp("No hay departamentos registrados", "Sistema");
           return;
        }
      
      
        String []aux = c.split("/");
        this.cmbDepartamentoR1.addItem("No seleccion");
        for (String x: aux){
             this.cmbDepartamentoR1.addItem(x);
        }
        
        
    }//GEN-LAST:event_cmdCargarDepartamento1ActionPerformed

    private void cmbDepartamentoR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoR1ActionPerformed
        // TODO add your handling code here:
        this.cmbMunicipioAlcalde.removeAllItems();
        if(this.cmbDepartamentoR1.getItemCount()!=0){
          String departamento = this.cmbDepartamentoR1.getSelectedItem().toString();
          if (!departamento.equalsIgnoreCase("No seleccion")){
            this.cmbMunicipioAlcalde.setEnabled(true);
            String municipio = this.myPrin.getMyCenso().consultarDepartamentoMunicipio(departamento);
            if (municipio.isEmpty()){
               Ventana.imp("No hay municipios con alcalde asignadomento", "Sistema");
               return;
             }
               String []aux = municipio.split("/");
               this.cmbMunicipioAlcalde.addItem("No seleccion");
               for (String x: aux){
                    this.cmbMunicipioAlcalde.addItem(x);
                    }
            }
        }
        
    }//GEN-LAST:event_cmbDepartamentoR1ActionPerformed

    private void cmbMunicipioAlcaldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMunicipioAlcaldeActionPerformed
        // TODO add your handling code here:
       
       if(this.cmbDepartamentoR1.getItemCount()!=0&&this.cmbMunicipioAlcalde.getItemCount()!=0){  
         String departamento = this.cmbDepartamentoR1.getSelectedItem().toString();
         String municipio=this.cmbMunicipioAlcalde.getSelectedItem().toString();
         if(!departamento.equalsIgnoreCase("No seleccion")&& !municipio.equalsIgnoreCase("No seleccion")){ 
            String infoMunicipio = this.myPrin.getMyCenso().consultarInfoDepartamentoM(departamento,municipio);
           this.txtMostrarMuni.setText(infoMunicipio);
           this.cmdEliminarAlcaldeM.setEnabled(true);
            
        }
            
       } 
    }//GEN-LAST:event_cmbMunicipioAlcaldeActionPerformed

    private void cmdEliminarAlcaldeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarAlcaldeMActionPerformed
        // TODO add your handling code here:
        if (this.cmbDepartamentoR1.getItemCount() > 0){
        String departamento = this.cmbDepartamentoR1.getSelectedItem().toString();
        String municipio = this.cmbMunicipioAlcalde.getSelectedItem().toString();
        
        String mensaje = this.myPrin.getMyCenso().eliminarAlcaldeMunicipio(departamento, municipio);
        Ventana.imp(mensaje, "Sistema");
        this.txtMostrarMuni.setText(""); 
        }
    }//GEN-LAST:event_cmdEliminarAlcaldeMActionPerformed

    private void cmbDepartamentoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartamentoRActionPerformed

    private void habilitarBotones() {
        this.txtTotalHombre.setEnabled(true);
        this.txtTotalMujeres.setEnabled(true);
        this.txtEdadPromedio.setEnabled(true);
        this.txtIngresoPromedio.setEnabled(true);
        this.txtTemperaturaMedia.setEnabled(true);
        this.cmbCategoria.setEnabled(true);
        this.txtCedulaAlcalde.setEnabled(true);
        this.cmdVeificarAlcalde.setEnabled(true);

    }

    private void deshabilitarBotones() {
        this.cmdVerificarMun.setEnabled(false);
        this.txtNombreM.setEnabled(false);
        this.txtTotalHombre.setEnabled(false);
        this.txtTotalMujeres.setEnabled(false);
        this.txtEdadPromedio.setEnabled(false);
        this.txtIngresoPromedio.setEnabled(false);
        this.txtTemperaturaMedia.setEnabled(false);
        this.cmbCategoria.setEnabled(false);
        this.txtCedulaAlcalde.setEnabled(false);
        this.cmdVeificarAlcalde.setEnabled(false);
        this.cmdRegistrar.setEnabled(false);

    }

    private void limpiar() {
        this.txtNombreM.setText("");
        this.txtTotalMujeres.setText("");
        this.txtTotalHombre.setText("");
        this.txtEdadPromedio.setText("");
        this.txtIngresoPromedio.setText("");
        this.txtTemperaturaMedia.setText("");
        this.txtCedulaAlcalde.setText("");
        this.cmbCategoria.setSelectedIndex(0);
    }

    public JButton getCmdRegistrar() {
        return cmdRegistrar;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JComboBox cmbDepartamentoR;
    private javax.swing.JComboBox cmbDepartamentoR1;
    private javax.swing.JComboBox cmbMunicipioAlcalde;
    private javax.swing.JButton cmbSalir;
    private javax.swing.JButton cmdCargarDepartamento;
    private javax.swing.JButton cmdCargarDepartamento1;
    private javax.swing.JButton cmdConsolidado;
    private javax.swing.JButton cmdEliminarAlcaldeM;
    private javax.swing.JButton cmdRegistrar;
    private javax.swing.JButton cmdReporte;
    private javax.swing.JButton cmdRequerientoQuiez;
    private javax.swing.JButton cmdVeificarAlcalde;
    private javax.swing.JButton cmdVerificarMun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCantidadIngresProm;
    private javax.swing.JTextField txtCedulaAlcalde;
    private javax.swing.JTextField txtEdadPromedio;
    private javax.swing.JTextField txtIngresoPromedio;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextArea txtMostrarConsolidado;
    private javax.swing.JTextArea txtMostrarMuni;
    private javax.swing.JTextField txtNombreM;
    private javax.swing.JTextField txtTemperaturaMedia;
    private javax.swing.JTextField txtTotalHombre;
    private javax.swing.JTextField txtTotalMujeres;
    // End of variables declaration//GEN-END:variables
}
