/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import conexion.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JScrollPane;
/**
 *
 * @author Astrid Caicedo
 */
public class Consulta extends javax.swing.JFrame {
    private InicioSesion inicio;
    /**
     * Creates new form Consulta
     */
    public Consulta(InicioSesion i) {
        initComponents();
        this.inicio = i;
        mostrar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cmbPro = new javax.swing.JComboBox<>();
        labelNombre1 = new javax.swing.JLabel();
        labeCc1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcionPro = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtNombrePro = new javax.swing.JTextField();
        cmdCargarPro = new javax.swing.JButton();
        labelNombre2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCantProd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cmdCargarCli = new javax.swing.JButton();
        cmbCli = new javax.swing.JComboBox<>();
        txtTele = new javax.swing.JTextField();
        txtCc = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDirecc = new javax.swing.JTextField();
        labeCc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescr = new javax.swing.JTextArea();
        txtFechaNac = new javax.swing.JTextField();
        labelNombre3 = new javax.swing.JLabel();
        cmdValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONSULTAS");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo 1.jpg"))); // NOI18N

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbPro.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        cmbPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- SELECIONE -", " " }));
        cmbPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProActionPerformed(evt);
            }
        });

        labelNombre1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        labelNombre1.setText("Nombre:");

        labeCc1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        labeCc1.setText("Precio:");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel7.setText("Descripcion:");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        cmdCargarPro.setBackground(new java.awt.Color(0, 153, 153));
        cmdCargarPro.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        cmdCargarPro.setText("Cargar Info");
        cmdCargarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarProActionPerformed(evt);
            }
        });

        labelNombre2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        labelNombre2.setText("ID PRODUCTO:");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel8.setText("cantidad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labeCc1)
                                .addComponent(labelNombre1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7))))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(cmdCargarPro)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantProd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(txtDescripcionPro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCargarPro)
                    .addComponent(labelNombre2))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeCc1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PRODUCTOS", jPanel2);

        cmdCargarCli.setBackground(new java.awt.Color(0, 153, 153));
        cmdCargarCli.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        cmdCargarCli.setText("Cargar Info");
        cmdCargarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarCliActionPerformed(evt);
            }
        });

        cmbCli.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        cmbCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- SELECIONE -", " " }));
        cmbCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliActionPerformed(evt);
            }
        });

        labeCc.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        labeCc.setText("Cedula:");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel3.setText("Descripcion:");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel4.setText("Direccion:");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel5.setText("Telefono:");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento:");

        labelNombre.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 16)); // NOI18N
        labelNombre.setText("Nombre:");

        textDescr.setEditable(false);
        textDescr.setColumns(20);
        textDescr.setRows(5);
        jScrollPane1.setViewportView(textDescr);

        labelNombre3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        labelNombre3.setText("CÉDULA PACIENTE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labeCc)
                        .addComponent(labelNombre3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelNombre))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(cmbCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                            .addComponent(cmdCargarCli)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCc, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(txtTele, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDirecc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre)
                                .addComponent(txtFechaNac))
                            .addGap(150, 150, 150)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCargarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeCc)
                    .addComponent(txtCc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PACIENTES", jPanel1);

        cmdValidar.setBackground(new java.awt.Color(10, 143, 143));
        cmdValidar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdValidar.setText("VOLVER");
        cmdValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(cmdValidar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdValidar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void cmdCargarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarProActionPerformed
        // TODO add your handling code here:
        mostrarInfoPro();
    }//GEN-LAST:event_cmdCargarProActionPerformed

    private void cmdCargarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarCliActionPerformed
        // TODO add your handling code here
        this.mostrarInfoCli();
    }//GEN-LAST:event_cmdCargarCliActionPerformed

    private void cmbProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProActionPerformed

    private void cmdValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_cmdValidarActionPerformed

    private void mostrar() {     
        this.cmbCli.removeAllItems();
        this.cmbPro.removeAllItems();
                      
        ResultSet rs = Database.getTabla("select cedula from clientes");
        ResultSet rs2 = Database.getTabla("select idProducto from productos");
        
        try {
            while (rs.next()) {
                this.cmbCli.addItem(rs.getString("cedula"));
                
            }            
            
            while (rs2.next()) {
                this.cmbPro.addItem(rs2.getString("idProducto"));
                
            } 
                       
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
    
    
    private void mostrarInfoPro()  {     
        
        String cli = this.cmbPro.getSelectedItem().toString();
        ResultSet rs = Database.getTabla("select nombreProducto,precio,descripcion,cantidad from productos where idProducto = "+cli);
        
        try {
            while (rs.next()) {
                
                this.txtNombrePro.setText(rs.getString("nombreProducto"));
                this.txtPrecio.setText(rs.getString("precio"));
                this.txtDescripcionPro.setText(rs.getString("descripcion"));
                this.txtCantProd.setText(rs.getString("cantidad"));
                
            }            
                       
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
     private void mostrarInfoCli()  {     
        
        String cli = this.cmbCli.getSelectedItem().toString();
        ResultSet rs = Database.getTabla("select nombre,cedula,direccion,fechaNac,telefono,descripcionAlergia from clientes where cedula = "+cli);
        
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                
                this.txtCc.setText(rs.getString("cedula"));
                this.textDescr.setText(rs.getString("descripcionAlergia"));
                this.txtDirecc.setText(rs.getString("direccion"));
                this.txtFechaNac.setText(rs.getString("fechaNac"));
                this.txtNombre.setText(rs.getString("nombre"));
                this.txtTele.setText(rs.getString("telefono"));
            }            
            // asigna el modelo a la tabla
                       
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCli;
    private javax.swing.JComboBox<String> cmbPro;
    private javax.swing.JButton cmdCargarCli;
    private javax.swing.JButton cmdCargarPro;
    private javax.swing.JButton cmdValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labeCc;
    private javax.swing.JLabel labeCc1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JTextArea textDescr;
    private javax.swing.JTextField txtCantProd;
    private javax.swing.JTextField txtCc;
    private javax.swing.JTextField txtDescripcionPro;
    private javax.swing.JTextField txtDirecc;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrePro;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
